### ISSUE TITLE
not supported thai philipine japan font unicode

### ISSUE THREAD

**Issue by wh-sugiharto** [BinBashBanana/html-obfuscator#1] opened 2021-01-27 23:52 UTC
closed case

**Comment by QuiteAFancyEmerald** [comment] 2021-01-28 01:31
Oh?

**Comment by BinBashBanana** [comment] 2021-01-28 01:41
It said it was their first case. They might not know when to close it. I will reopen it now, and handle it soon.

(You close it when the issue is resolved)

**Comment by BinBashBanana** [comment] 2021-01-28 23:38
Fixed! (garbled text is now fixed as well)

**Closed as completed by BinBashBanana** 2021-01-28 23:38 UTC
